library("downloader")
library("smatr")
library("maps")
library("mapdata")
library("baad.data")
source("R/figures.R")
source("R/utils.R")
dir.create("downloads", FALSE, TRUE)
dir.create("output", FALSE, TRUE)
baad <- baad_data("1.0.0")
library("knitr")
knitr::knit("report.Rmd", "report.md")
library("rmarkdown")
render("report.md", "html_document", quiet = TRUE, output_dir = "output")
pdf("output/map.pdf", width = 9L, height = 4L)
figure_map(baad)
dev.off()
pdf("output/fig_count.pdf", height = 6L, width = 8L)
figure_count(baad)
dev.off()
pdf("output/fig_allometry.pdf", width = 3L, height = 3L)
fig_allometry(baad)
dev.off()
summary <- table_summary(baad)
write.csv(summary, "output/summary.csv", row.names = FALSE)
